name: Push code to Lambda
on:
  push:
    branches:
      - main  

permissions:
  id-token: write
  contents: read

jobs:
  update-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.14"

      - name: Zip Lambda function
        run: |
          # Zip all files in the folder
          zip -r function.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update Lambda code
        run: |
          aws lambda update-function-code \
            --function-name carBackend \
            --zip-file fileb://function.zip \
            --query 'FunctionArn' \
            --output text